import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/globals.css";
import { Toaster } from "@/common/components/ui/sonner";
import { Blog } from "@blogs/models";

const geistSans = localFont({
  src: "../common/assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "500 700",
});
const geistMono = localFont({
  src: "../common/assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "500 700",
});

export const metadata: Metadata = {
  title: "Next app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster richColors  />
      </body>
    </html>
  );
}
